# Generated by Django 4.0.3 on 2022-04-02 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_alter_photo_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='author',
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ManyToManyField(related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
        migrations.AddField(
            model_name='photo',
            name='author',
            field=models.ManyToManyField(related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
