# Generated by Django 4.0.3 on 2022-04-02 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_remove_album_author_album_author_remove_photo_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='selected',
            field=models.ManyToManyField(related_name='selected_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
