# Generated by Django 4.0.3 on 2022-04-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_photo_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
